# Generated by Django 4.2.17 on 2025-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_item_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('position', models.CharField(choices=[('top', 'Верхняя реклама'), ('bottom', 'Нижняя реклама')], max_length=10)),
            ],
        ),
    ]
