# Generated by Django 4.2.17 on 2025-02-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_attribute_attributevalue_itemattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Значение атрибута', 'verbose_name_plural': 'Значения атрибутов'},
        ),
        migrations.AlterModelOptions(
            name='itemattributevalue',
            options={'verbose_name': 'Значение атрибута товара', 'verbose_name_plural': 'Значения атрибутов товаров'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='attributes',
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='value',
            field=models.CharField(default='Без значения', max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='itemattributevalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='store.item', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название атрибута')),
                ('type', models.CharField(choices=[('dropdown', 'Выпадающий список'), ('radio', 'Радио-кнопка'), ('checkbox', 'Флажок'), ('text', 'Текстовое поле'), ('number', 'Числовое поле'), ('color', 'Выбор цвета')], max_length=20, verbose_name='Тип атрибута')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('tags', models.ManyToManyField(related_name='attributes', to='store.itemtag', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Атрибут товара',
                'verbose_name_plural': 'Атрибуты товаров',
            },
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.itemattribute', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.itemattribute', verbose_name='Атрибут'),
        ),
        migrations.AlterUniqueTogether(
            name='itemattributevalue',
            unique_together={('item', 'attribute')},
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='attribute_value',
        ),
    ]
