# Generated by Django 4.2.17 on 2025-02-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemattributevalue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название атрибута'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательный атрибут'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='store.itemtag', verbose_name='Категории (теги)'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('radio', 'Radio'), ('color', 'Color'), ('text', 'Text')], max_length=50, verbose_name='Тип атрибута'),
        ),
        migrations.AlterField(
            model_name='itemattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemattribute'),
        ),
        migrations.AlterField(
            model_name='itemattributevalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='store.item'),
        ),
        migrations.AlterField(
            model_name='itemattributevalue',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
