# Generated by Django 4.2.17 on 2025-02-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_item_wholesale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя атрибута')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.item', verbose_name='Товар')),
            ],
        ),
    ]
