# Generated by Django 4.2.17 on 2025-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество в наличии'),
        ),
    ]
