# Generated by Django 4.2.17 on 2025-02-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название атрибута')),
                ('type', models.CharField(choices=[('dropdown', 'Выпадающий список'), ('radio', 'Радиокнопки'), ('text', 'Текстовое поле'), ('color', 'Выбор цвета')], max_length=20, verbose_name='Тип атрибута')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='value',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='price_modifier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Модификатор цены'),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='attribute_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.attributevalue', verbose_name='Значение атрибута'),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attribute', verbose_name='Атрибут'),
        ),
        migrations.DeleteModel(
            name='ItemAttribute',
        ),
    ]
