# Generated by Django 4.2.17 on 2025-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_attribute_remove_itemattribute_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemtag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
