# Generated by Django 4.2.17 on 2025-02-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_itemtag_name_alter_itemtag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattributevalue',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attribute')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemtag')),
            ],
            options={
                'unique_together': {('attribute', 'tag')},
            },
        ),
    ]
