# Generated by Django 4.2.17 on 2025-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_itemattributevalue_quantity_attributecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('dropdown', 'Выпадающий список'), ('checkbox', 'Чекбоксы'), ('text', 'Текстовое поле'), ('color', 'Выбор цвета')], max_length=20, verbose_name='Тип атрибута'),
        ),
    ]
