# Generated by Django 4.2.17 on 2025-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_item_video_alter_attribute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='to_order',
            field=models.BooleanField(default=False, verbose_name='Под заказа'),
        ),
    ]
