# Generated by Django 4.2.17 on 2025-02-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_item_to_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец'},
        ),
    ]
