# Generated by Django 4.2.17 on 2025-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='attributes',
            field=models.JSONField(default=dict, verbose_name='Атрибуты'),
        ),
    ]
