# Generated by Django 4.2.17 on 2025-02-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderitem_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='attributes',
        ),
    ]
