# Generated by Django 4.2.17 on 2025-02-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_attribute_remove_itemattribute_tags_and_more'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='store.itemattributevalue'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
    ]
