# Generated by Django 4.2.17 on 2025-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_attribute_values_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
